### PR TITLE
fix(ProcFile): get procfile from the slug if it is not provided

### LINKED ISSUE #213: Custom BUILDPACK_URL doesn't work
Deploying [example-perl](https://github.com/deis/example-perl) on current Deis v2 fails:
```console
$ cd example-perl
$ deis create --buildpack https://github.com/miyagawa/heroku-buildpack-perl.git
Creating Application... done, created guided-question
Git remote deis added
remote available at ssh://git@deis.192.168.64.2.xip.io:2222/guided-question.git
$ deis config
=== guided-question Config
BUILDPACK_URL      https://github.com/miyagawa/heroku-buildpack-perl.git
$ git push deis master
Counting objects: 41, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (36/36), done.
Writing objects: 100% (41/41), 11.10 KiB | 0 bytes/s, done.
Total 41 (delta 12), reused 0 (delta 0)
remote: 2016/03/01 04:03:39 Running in debug mode
Running git hook
read [0000000000000000000000000000000000000000,eaed0559111ca65588ec24897316faf8d9007a38,refs/heads/master]
Workflow request /v2/hooks/push (body elided)
Workflow request POST /v2/hooks/config
{"receive_user":"matt","receive_repo":"guided-question"}
got the following config back for app guided-question: {Owner:matt App:guided-question Values:map[BUILDPACK_URL:https://github.com/miyagawa/heroku-buildpack-perl.git] Memory:map[] CPU:map[] Tags:map[] UUID:9ec0e2aa-0598-44b5-8116-ef67b8b9e776 Created:2016-03-01 04:03:24 +0000 UTC Updated:2016-03-01 04:03:24 +0000 UTC}
found custom buildpack URL https://github.com/miyagawa/heroku-buildpack-perl.git
running [git archive --format=tar.gz --output=guided-question.tar.gz eaed0559] in directory /home/git/guided-question.git
remote: 2016/03/01 04:03:39 Error running git receive hook [reading /home/git/guided-question.git/build/tmp999357363/Procfile]
running [tar -xzf guided-question.tar.gz -C /home/git/guided-question.git/build/tmp999357363/] in directory /home/git/guided-question.git
To ssh://git@deis.192.168.64.2.xip.io:2222/guided-question.git
 * [new branch]      master -> master
```

### PR DESCRIPTION
**Pull request by kmala**
fixes https://github.com/deis/builder/issues/213

### CODE REVIEW

**Comment by arschles** [comment]
@kmala is this ready for review?

**Comment by kmala** [comment]
@arschles yes.
I have to add an e2e test to test this scenario which i am currently doing.

File: rootfs/builder/build.sh [hunk 1]
```diff
@@ -189,6 +189,14 @@ else
     tar -z --exclude='.git' -C $build_root -cf $slug_file . | cat
 fi
 
+if [[ ! -f "$build_root/Procfile" ]]; then
+	if [[ -s "$build_root/.release" ]]; then
+		ruby -e "require 'yaml';procTypes = (YAML.load_file('$build_root/.release')['default_process_types']);open('$build_root/Procfile','w') {|f| YAML.dump(procTypes,f)}"
```
Comment (arschles) [inline rootfs/builder/build.sh:194]: @kmala this logic seems to be filling in a default procfile. Wouldn't this make more sense to do in the builder?

Comment (kmala) [inline rootfs/builder/build.sh:194]: @arschles i had thought about it but for us to do it in the builder we need to download the the slug.tgz which is much bigger than a Procfile

Comment (arschles) [inline rootfs/builder/build.sh:194]: @kmala good point, but can the builder create it before it creates and uploads the tar?

Comment (kmala) [inline rootfs/builder/build.sh:194]: @arschles builder can't because the default proctypes will be present in the build-pack which is detected in the slugbuilder

Comment (arschles) [inline rootfs/builder/build.sh:194]: Ah, got it. Thanks for spelling it out for me!

**Comment by arschles** [comment]
@kmala code lgtm. Also, note that I've removed the `in progress` label because it was confusing before.

**Comment by kmala** [comment]
Thanks @arschles .Can you also review the corresponding changes in the builder https://github.com/deis/builder/pull/239

**Comment by arschles** [comment]
@kmala yes, I'll look now

**Comment by arschles** [comment]
@kmala I've added the beta milestone to this PR since #213 is under beta.

**Comment by mboersma** [comment]
I tested this with deis/builder#239 and example-perl as described in the original bug. Works great now.
